services:
  chocolate-api:
    container_name: chocolate-api
    image: node:20
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    working_dir: /app
    volumes:
      - ./api:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"
    tty: true
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chocolate_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

  redis:
    container_name: redis
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:

